FROM ubuntu:20.04

# Let us install tzdata painlessly
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    neovim \
    python3-pip \
    apt-utils \
    git \
    python-is-python3

# Copy requirements file
COPY requirements-leaderboard.txt /tmp/

# Install Python dependencies
RUN pip install --upgrade pip \
 && pip install -r /tmp/requirements-leaderboard.txt

RUN pip install carla

# Get the Leaderboard
RUN cd /opt \
 && git clone --single-branch https://github.com/carla-simulator/leaderboard.git \
 && echo "LEADERBOARD_ROOT=/opt/leaderboard" >> ~/.bashrc

# Get the Scenario Runner
RUN cd /opt \
 && git clone --single-branch https://github.com/carla-simulator/scenario_runner.git \
 && echo "SCENARIO_RUNNER_ROOT=/opt/scenario_runner" >> ~/.bashrc

