ARG CARLA_VER=0.9.15
FROM carlasim/carla:${CARLA_VER}

ARG CARLA_VER

USER root

# Let us install tzdata painlessly
ENV DEBIAN_FRONTEND=noninteractive

# RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub

RUN apt-get update && apt-get install -y --no-install-recommends \
    vulkan-utils \
    neovim \
    libjpeg8 \
    libtiff5 \
    xdg-user-dirs \
    apt-utils

