ARG ROS_VER=humble
FROM osrf/ros:${ROS_VER}-simulation

ARG ROS_VER
ENV ROS_VER ${ROS_VER}

# Let us install tzdata painlessly
ENV DEBIAN_FRONTEND=noninteractive

# # Remove the outdated signing key
# RUN apt-key del 7fa2af80
# 
# # Install the new cuda-keyring package
# RUN wget https://developer.download.nvidia.com/compute/cuda/repos/$distro/$arch/cuda-keyring_1.0-1_all.deb \
#     dpkg -i cuda-keyring_1.0-1_all.deb

RUN apt-get update && apt-get install -y --no-install-recommends \
    neovim \
    python3-pip \
    apt-utils 
#    ros-humble-ros-environment

# Copy requirements file
COPY requirements-ros.txt /tmp/

# Install Python dependencies
RUN pip install --upgrade pip \
 && pip install -r /tmp/requirements-ros.txt

# ROS Bridge Installation

SHELL ["/bin/bash", "-c"]

RUN cd /opt/ros/${ROS_VER}/include/tf2_eigen/ \
 && cp tf2_eigen/* ./

RUN mkdir -p /opt/carla-ros-bridge && cd /opt/carla-ros-bridge \
 && git clone --recurse-submodules https://github.com/carla-simulator/ros-bridge.git src/ros-bridge

RUN cd /opt/carla-ros-bridge/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge \
 && sed -i "s/0.9.13/0.9.15/g" CARLA_VERSION

# RUN source /opt/ros/${ROS_VER}/setup.bash

RUN source /opt/ros/${ROS_VER}/setup.bash \
 && cd /opt/carla-ros-bridge \
 && rosdep update \
 && rosdep install --from-paths src --ignore-src -r -y

RUN source /opt/ros/${ROS_VER}/setup.bash \
 && cd /opt/carla-ros-bridge \
 && colcon build

# Source the ROS setup.bash script
RUN echo "source /opt/ros/${ROS_VER}/setup.bash" >> ~/.bashrc \
 && echo "source /opt/carla-ros-bridge/install/setup.bash" >> ~/.bashrc

